1.sql
account.sql
AllTables.sql
category.sql
currency.sql
customer.sql
days.sql
deleteTables.sql
department.sql
derby.log
employee.sql
employee_closure.sql
expense_fact.sql
FoodMartCreateData.sql
helloDB
inventory_fact_1997.sql
inventory_fact_1998.sql
javaDB_space
position.sql
product.sql
product_class.sql
promotion.sql
region.sql
reserve_employee.sql
run.bat
salary.sql
sales_fact_1997.sql
sales_fact_1998.sql
sales_fact_dec_1998.sql
selectAccount.sql
selectStore.sql
store.sql
store_ragged.sql
time_by_day.sql
warehouse.sql
warehouse_class.sql
